version: '3'
services:
  mysql:
    container_name: pfsign_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MySQL=server=mysql;userid=root;pwd=password;port=3306;database=PFSignDev;"