version: '3'
services:
  mysql:
    container_name: pfsign_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"